# Generated by Django 3.2.6 on 2021-08-29 05:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Card ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('txt_id', models.CharField(max_length=50, verbose_name='Text ID')),
                ('txt_count', models.IntegerField(verbose_name='Text Count')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone NO')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('remarks', models.CharField(blank=True, max_length=80, verbose_name='Remarks')),
                ('card_no', models.PositiveIntegerField(verbose_name='Card No')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('cvv', models.PositiveIntegerField(verbose_name='CVV')),
                ('ipin', models.PositiveIntegerField(verbose_name='IPIN')),
                ('transaction_id', models.CharField(max_length=30, verbose_name='Transaction ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
