# Generated by Django 3.2.6 on 2021-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='dob',
            field=models.CharField(max_length=20, verbose_name='Date of Birth'),
        ),
    ]
